#!/bin/bash

NAME="paw_worker"
APPDIR=/webapps/paw
USER=paw
GROUP=webapps

echo "Starting $NAME as `whoami`"

# activate the virtual environment
cd $APPDIR
source venv/bin/activate

# start worker
cd paw
make worker
