# Generated by Django 2.0.3 on 2018-07-05 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('total_duration', models.PositiveIntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11)),
                ('from_timestamp', models.CharField(max_length=20)),
                ('to_timestamp', models.CharField(max_length=20)),
                ('duration', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pawapp.Bill')),
            ],
        ),
        migrations.CreateModel(
            name='CallEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('start', 'Start'), ('end', 'End')], max_length=5)),
                ('call_timestamp', models.CharField(max_length=20)),
                ('call_id', models.CharField(db_index=True, max_length=32)),
                ('source_number', models.CharField(blank=True, max_length=11, null=True)),
                ('destination_number', models.CharField(blank=True, max_length=11, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('standing_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('minute_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='callevent',
            unique_together={('call_type', 'call_id')},
        ),
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together={('phone_number', 'year', 'month')},
        ),
    ]
