# Generated by Django 2.0.3 on 2018-03-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=16)),
                ('call_type', models.CharField(choices=[('start', 'Start'), ('end', 'End')], max_length=5)),
                ('call_timestamp', models.DateTimeField()),
                ('call_id', models.CharField(max_length=16)),
                ('source_number', models.CharField(blank=True, max_length=9, null=True)),
                ('destination_number', models.CharField(blank=True, max_length=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
