# Generated by Django 2.0.3 on 2018-03-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callevent',
            name='event_id',
        ),
        migrations.AlterField(
            model_name='callevent',
            name='call_id',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='callevent',
            name='destination_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='callevent',
            name='source_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
