# Generated by Django 2.0.3 on 2018-04-03 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pawapp', '0002_auto_20180327_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11)),
                ('from_time', models.DateTimeField()),
                ('to_time', models.DateTimeField()),
                ('duration', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pawapp.Bill')),
            ],
        ),
        migrations.RenameField(
            model_name='connectionrate',
            old_name='rate',
            new_name='minute_rate',
        ),
        migrations.AddField(
            model_name='connectionrate',
            name='standing_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='callevent',
            name='call_id',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='callevent',
            unique_together={('call_type', 'call_id')},
        ),
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together={('phone_number', 'year', 'month')},
        ),
    ]
