# Generated by Django 2.0.3 on 2018-04-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawapp', '0003_auto_20180403_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
    ]
