# Generated by Django 2.0.3 on 2018-04-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawapp', '0004_auto_20180416_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callevent',
            name='call_timestamp',
            field=models.CharField(max_length=20),
        ),
    ]
