# Generated by Django 2.0.3 on 2018-03-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callevent',
            name='call_type',
            field=models.CharField(choices=[('start', 'Start'), ('start', 'End')], max_length=5),
        ),
    ]
