# Generated by Django 2.0.3 on 2018-03-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180322_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callevent',
            name='destination_number',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='callevent',
            name='source_number',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
